server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name:
                fallbackuri: forward:/userServiceFallback
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contacts/**
          filters:
            - name: CircuitBreaker
              args:
                name:
                fallbackuri: forward:/contactServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieSeconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

